name: Daily Blog Notifier

on:
  schedule:
    - cron: '0 8 * * *'  # runs every day at 8:00 UTC
  workflow_dispatch:

jobs:
  check-for-new-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Run notifier script
        run: python notifier.py
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit last_post.txt if changed
        run: |
          if [[ -f last_post.txt ]]; then
            git add last_post.txt
            git commit -m "Update last seen post" || echo "No changes to commit"
            git push
          fi

